# Generated by Django 5.0.3 on 2024-04-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='customer',
        ),
    ]
