# Generated by Django 5.0.3 on 2024-04-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tools_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='order',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
