# Generated by Django 5.0.3 on 2024-04-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.IntegerField(choices=[(1, 'Construction Equipment'), (2, 'Drilling Equipment'), (3, 'Transportation Equipment'), (4, 'Agriculture Equipment'), (5, 'Electrical Equipment'), (6, 'Maintenance Equipment')])),
            ],
        ),
        migrations.AddField(
            model_name='tools',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categories'),
        ),
    ]
